aprendiz/urls.py
from django.urls import path
from aprendiz import views

app_name = "aprendiz"
urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('crear-preguntas/', views.CrearPregunta.as_view(), name="crearPreguntas"),
    path('editar_perfil/<int:pk>/', views.EditarPerfil.as_view(), name="editarPerfil"),
    path('eliminar_perfil/', views.EliminarPerfil.as_view(), name="eliminarPerfil"),
    path('preguntas/', views.VerPreguntas.as_view(), name="verPreguntas"),
    path('comentario/', views.InsertarComentario.as_view(), name="comentario")
]

foroStudent/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeDoneView, PasswordChangeView, PasswordResetView, \
    PasswordResetConfirmView, PasswordResetCompleteView, PasswordResetDoneView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from principal.views import Login, Logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('principal.urls', namespace="principal"), name="principal"),
    path('accounts/', include('aprendiz.urls', namespace="aprendiz"), name="aprendiz"),
    path('backoffice/', include('instructor.urls', namespace="instructor"), name="instructor"),
    path('login/', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),

    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<str:uidb64>/<str:token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instructor/urls.py
from django.urls import path
from instructor import views

app_name = "instructor"
urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('editar_perfil/<int:pk>/', views.EditarPerfil.as_view(), name="editarPerfil"),
    path('preguntas/', views.VerPreguntas.as_view(), name="verPreguntas"),
    path('comentario/', views.InsertarComentario.as_view(), name="comentario"),
    path('lista-aprendices/', views.VerAprendices.as_view(), name="aprendices")
]

principal/urls.py
from django.urls import path
from principal import views

app_name = "principal"
urlpatterns = [
    path('', views.inicio, name="index"),
    path('introducion/', views.introducion, name="introduccion"),
    path('justificacion/', views.justificacion, name="justificacion"),
    path('contacto/', views.contacto, name="contacto"),
    path('registro/', views.Registro.as_view(), name="registro"),
]

templates/layouts/alertas.html
<div class="alerts">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger">
                    <a href="#" class="close" data-dismiss="alert">&times;</a>
                    <strong>ERROR!</strong> {{ message }}
                </div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                <div class="alert alert-warning ">
                    <a href="#" class="close" data-dismiss="alert">&times;</a>
                    <strong>ADVERTENCIA !</strong> {{ message }}
                </div>
            {% else %}
                <div class="alert alert-success">
                    <a href="#" class="close" data-dismiss="alert">&times;</a>
                    <strong>FELICITACIONES !</strong> {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>

templates/layouts/plantilla_aprendiz.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style-principal.css' %}">
    {% block styles %}

    {% endblock %}
</head>
<body>

    <header>
      <div class="container">
          <div class="jumbotron text-center" style="margin-bottom:0">
            <h1>Student Intelligent</h1>
            <div id ='logo'> </div>

          </div>
      </div>
    </header>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <a class="navbar-brand" href="{% url 'principal:index' %}">Student Intelligent</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'aprendiz:index' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'aprendiz:crearPreguntas' %}">Preguntas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'aprendiz:verPreguntas' %}">Respuestas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Salir</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container">
        {% block contenido %}

        {% endblock %}
    </div>
    <div class="container">
        <footer>
            <div class="jumbotron text-center" style="margin-bottom:0">
                <p>Derechos Reservador SENA 2018</p>
            </div>
        </footer>
    </div>


    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

templates/layouts/plantilla_instructor.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style-principal.css' %}">
    {% block styles %}

    {% endblock %}
</head>
<body>

    <header>
      <div class="container">
          <div class="jumbotron text-center" style="margin-bottom:0">
            <h1>Student Intelligent</h1>
            <div id ='logo'> </div>

          </div>
      </div>
    </header>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <a class="navbar-brand" href="{% url 'principal:index' %}">Student Intelligent</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'instructor:index' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'instructor:verPreguntas' %}">Preguntas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'instructor:aprendices' %}">Aprendices</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Salir</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container">
        {% block contenido %}

        {% endblock %}
    </div>
    <div class="container">
        <footer>
            <div class="jumbotron text-center" style="margin-bottom:0">
                <p>Derechos Reservador SENA 2018</p>
            </div>
        </footer>
    </div>


    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

templates/layouts/plantilla_principal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style-principal.css' %}">
    {% block styles %}
    
    {% endblock %}
</head>
<body>

    <header>
      <div class="container">
          <div class="jumbotron text-center" style="margin-bottom:0">
            <h1>Student Intelligent</h1>
            <div id ='logo'> </div>

          </div>
      </div>
    </header>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <a class="navbar-brand" href="{% url 'principal:index' %}">Student Intelligent</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'principal:index' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'principal:introduccion' %}">Introducción</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'principal:justificacion' %}">Justificación</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'principal:contacto' %}">Contactos</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container">
        {% block contenido %}
        
        {% endblock %}
    </div>
    <div class="container">
        <footer>
            <div class="jumbotron text-center" style="margin-bottom:0">
                <p>Derechos Reservador SENA 2018</p>
            </div>
        </footer>
    </div>


    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block scripts %}{% endblock %}
</body>
</html>