aprendiz/urls.py
from django.urls import path
from aprendiz import views

app_name = "aprendiz"
urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('crear-preguntas/', views.CrearPregunta.as_view(), name="crearPreguntas"),
    path('editar_perfil/<int:pk>/', views.EditarPerfil.as_view(), name="editarPerfil"),
    path('eliminar_perfil/', views.EliminarPerfil.as_view(), name="eliminarPerfil"),
    path('preguntas/', views.VerPreguntas.as_view(), name="verPreguntas"),
    path('comentario/', views.InsertarComentario.as_view(), name="comentario")
]

foroStudent/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeDoneView, PasswordChangeView, PasswordResetView, \
    PasswordResetConfirmView, PasswordResetCompleteView, PasswordResetDoneView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from principal.views import Login, Logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('principal.urls', namespace="principal"), name="principal"),
    path('accounts/', include('aprendiz.urls', namespace="aprendiz"), name="aprendiz"),
    path('backoffice/', include('instructor.urls', namespace="instructor"), name="instructor"),
    path('login/', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),

    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<str:uidb64>/<str:token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

principal/urls.py
from django.urls import path
from principal import views

app_name = "principal"
urlpatterns = [
    path('', views.inicio, name="index"),
    path('introducion/', views.introducion, name="introduccion"),
    path('justificacion/', views.justificacion, name="justificacion"),
    path('contacto/', views.contacto, name="contacto"),
    path('registro/', views.Registro.as_view(), name="registro"),
]

principal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

DOC_CHOICES = [
    ('CC','Cedula ciudadania'),
    ('CE','Cedula extranjera'),
    ('O',"Otro"),
]
ROL_CHOICES = [
    ("APR","Aprendiz"),
    ("INS","Instructor"),
]


class InformacionPersonal(models.Model):
    id = models.AutoField(primary_key=True)
    userid = models.OneToOneField(User, on_delete=models.CASCADE) #foranea a modelo User
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    tipo_documento = models.CharField(max_length=20, choices=DOC_CHOICES, default="CC")
    num_documento = models.CharField(max_length=20)
    rol = models.CharField(max_length=30, choices=ROL_CHOICES, default="APR")
    foto = models.ImageField(upload_to="perfiles/", null=True)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return "%s %s"%(self.nombre,self.apellidos)

    class Meta:
        verbose_name = "Informacion Personal"
        verbose_name_plural = "Informacion Personales"


class Pregunta(models.Model):
    id = models.AutoField(primary_key=True)
    userid = models.ForeignKey(InformacionPersonal, on_delete=models.CASCADE, null=True)
    titulo = models.CharField(max_length=50)
    descripcion = models.TextField()
    fecha = models.DateField(default=timezone.now)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return "%s"%(self.titulo)

    class Meta:
        verbose_name = "Pregunta"
        verbose_name_plural = "Preguntas"
        ordering = ['-id']


class Comentario(models.Model):
    id = models.AutoField(primary_key=True)
    userid = models.ForeignKey(InformacionPersonal, on_delete=models.CASCADE)
    pregid = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    contenido = models.TextField()
    fecha = models.DateField(default=timezone.now)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return "%s | %s"% (self.userid, self.pregid)

    class Meta:
        verbose_name = "Comentario"
        verbose_name_plural = "Comentarios"
        ordering = ['-id']


class Respuesta(models.Model):
    id = models.AutoField(primary_key=True)
    userid = models.ForeignKey(InformacionPersonal, on_delete=models.CASCADE)
    pregid = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    comid = models.ForeignKey(Comentario, on_delete=models.CASCADE) # foranea a comentario
    contenido = models.TextField()

    estado = models.BooleanField(default=True)

    def __str__(self):
        return "%s | %s > %s"%(self.userid, self.pregid, self.comid)

    class Meta:
        verbose_name = "Respuesta de Comentario"
        verbose_name_plural = "Respuestas de Comentarios"

principal/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from principal.models import InformacionPersonal
from django.contrib.auth.models import User

class RegistroUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "password",
        ]
        label = {
            "username": "Nombre de usuario",
            "email": "Correo Electronico",
            "password": "Contraseña",
        }

    def __init__(self, *args, **kwargs):
        super(RegistroUserForm, self).__init__(*args, **kwargs)

        for field in self.fields:

            self.fields[field].widget.attrs.update({'class': 'form-control'})

class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email"
        ]
        label = {
            "username": "Nombre de usuario",
            "email": "Correo Electronico"
        }

    def __init__(self, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)

        for field in self.fields:

            self.fields[field].widget.attrs.update({'class': 'form-control'})

class RegistroDatosForm(forms.ModelForm):
    class Meta:
        model = InformacionPersonal

        fields = [
            "nombre",
            "apellidos",
            "tipo_documento",
            "num_documento",
            "rol",
            "foto",

        ]
        label = {
            "nombre": "Nombre",
            "apellidos": "Apellidos",
            "tipo_documento": "Tipo de documento",
            "num_documento": " Numero de documento",
            "rol": "Rol de usuario",
            "foto": "Fotografia"
        }

    def __init__(self,rol=None, *args, **kwargs):
        super(RegistroDatosForm, self).__init__(*args, **kwargs)

        if not rol is None:
            self.fields["rol"].initial = rol
            self.fields["rol"].widget = forms.HiddenInput()
            self.fields["rol"].widget.attrs.update({'class':'form-control'})

        for field in self.fields:

            self.fields[field].widget.attrs.update({'class': 'form-control'})
        self.fields["foto"].widget.attrs.update({'class': 'd-block'})

principal/views.py
from django.contrib import auth, messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView
from django.contrib.auth.models import User
from django.views.generic.base import View
from principal.models import InformacionPersonal
from principal import forms




# Create your views here.
class Registro(CreateView):
    model = User
    template_name = "principal/registro.html"
    form_class = forms.RegistroDatosForm
    form2_class = forms.RegistroUserForm
    success_url = reverse_lazy("principal:index")

    def get_context_data(self, **kwargs):
        context = super(Registro, self).get_context_data(**kwargs)

        context['form'] = self.form_class(None, self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.form2_class(self.request.GET)

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(None,self.request.POST, self.request.FILES)
        form2 = self.form2_class(self.request.POST)

        if form.is_valid() and form2.is_valid():
            datosPersonales = form.save(commit=False) # no guarda lo tiene ya en lista
            datosPersonales.userid = form2.save()
            datosPersonales.save()

            messages.add_message(request, messages.SUCCESS, "El usuario se ha creado exitosamente ;)")

            return HttpResponseRedirect(self.get_success_url())
        else:
            messages.add_message(request,messages.ERROR,"recuerda rellenar todos los campos porfavor")
            messages.add_message(request, messages.WARNING, "Nota: si has editado el usuario podria ya estar en uso")

            return self.render_to_response(self.get_context_data(form=form, form2=form2))

class Login(View):
    def get(self,request):
        return HttpResponseRedirect(reverse("principal:index"))
    def post(self, request):
        username = request.POST.get("username", "").lower()
        password = request.POST.get("password", "")

        if username == "" and password == "":
            messages.add_message(request, messages.WARNING, "los campos no pueden estar vacios porfavor rellenarlos si es tan amable")
            return HttpResponseRedirect(reverse("principal:index"))

        user = auth.authenticate(username=username, password=password)
        if not user is None:
            auth.login(request, user)


            try:
                datos_personales = InformacionPersonal.objects.get(userid=user.pk)
            except InformacionPersonal.DoesNotExist:
                messages.add_message(request, messages.ERROR, "lo sentimos no hemos ubicado tus datos, comunicate con el administrador")
                return HttpResponseRedirect(reverse("logout"))

            if datos_personales.rol == "INS":
                return HttpResponseRedirect(reverse("instructor:index"))
            else:
                return HttpResponseRedirect(reverse("aprendiz:index"))

        else:
            messages.add_message(request, messages.ERROR, "usuario o contraseña incorrectos")

        return HttpResponseRedirect(reverse("principal:index"))

def inicio(request):

    try:
        datos_personales = InformacionPersonal.objects.get(userid=request.user.pk)
        rol = datos_personales.rol
    except:
        rol = None

    return render(request, 'principal/index.html',{"rol": rol})
def introducion(request):
    return render(request, 'principal/introduccion.html')
def justificacion(request):
    return render(request, 'principal/justificacion.html')
def contacto(request):
    return render(request, 'principal/contacto.html')

class Logout(View):
    def get(self, request):
        auth.logout(request)
        return HttpResponseRedirect(reverse('login'))

templates/principal/contacto.html
{% extends 'layouts/plantilla_principal.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/style-instructor.css' %}">
{% endblock %}
{% block contenido %}

<section id="contact">
    <div class="container wow fadeInUp">
        <div class="section-header">
            <h3 class="section-title">Contactanos</h3>
            <p class="section-description">Encuentra todo los eventos disponibles en Pereira y su area metropolitana</p>
        </div>
    </div>
    <div class="container wow fadeInUp mt-5">
        <div class="row justify-content-center">

            <div class="col-lg-3 col-md-4">
                <div class="info">
                    <div>
                        <i class="fa fa-map-marker"></i>
                        <p>SENA Regional<br>Dosquebradas-Risaralda</p>
                    </div>

                    <div>
                        <i class="fa fa-envelope"></i>
                        <p>info@example.com</p>
                    </div>

                    <div>
                        <i class="fa fa-phone"></i>
                        <p>+57 333 7777 77</p>
                    </div>
                </div>

            </div>

            <div class="col-lg-5 col-md-8">
                <div class="form">
                    <div id="sendmessage">Tu mensaje ha sido enviado. ¡Gracias!</div>
                    <div id="errormessage"></div>
                    <form action="" method="post" role="form" class="contactForm">
                        <div class="form-group">
                            <input type="text" name="name" class="form-control" id="name" placeholder="Nombre" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                            <div class="validation"></div>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" name="email" id="email" placeholder="Correo" data-rule="email" data-msg="Please enter a valid email" />
                            <div class="validation"></div>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="subject" id="subject" placeholder="Telefono" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                            <div class="validation"></div>
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Mensaje"></textarea>
                            <div class="validation"></div>
                        </div>
                        <div class="text-center"><button type="submit">Enviar mensaje</button></div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</section><!-- #contact -->
{% endblock %}

templates/principal/index.html
{% extends 'layouts/plantilla_principal.html' %}
{% load  static %}
{% block contenido %}
<section>

    <div style="margin-top:50px">
        <div class="row">
            <div class="col-sm-8">
                <h2>Imagenes</h2>
                <div id="demo" class="carousel slide" data-ride="carousel">

                    <!-- Indicators -->
                    <ul class="carousel-indicators">
                        <li data-target="#demo" data-slide-to="0" class="active"></li>
                        <li data-target="#demo" data-slide-to="1"></li>
                        <li data-target="#demo" data-slide-to="2"></li>
                    </ul>

                    <!-- The slideshow -->
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="{% static 'imagenes/4545168.jpg' %}" class="img-fluid">
                        </div>
                        <div class="carousel-item">
                            <img src="{% static 'imagenes/6786872.jpg' %}" class="img-fluid">
                        </div>
                        <div class="carousel-item">
                            <img src="{% static 'imagenes/64785.jpg' %}" class="img-fluid">
                        </div>
                    </div>

                    <!-- Left and right controls -->
                    <a class="carousel-control-prev" href="#demo" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                    </a>
                    <a class="carousel-control-next" href="#demo" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                    </a>

                </div>

            </div>





            {% if not user.is_authenticated %}
            <div class="col-sm-4">
                <h2>login</h2>
                {% include 'layouts/alertas.html' %}
                <form action="{% url 'login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="email">Email o username:</label>
                        <input type="text" class="form-control" id="email" name="username">
                    </div>

                    <div class="form-group">
                        <label for="pwd">Password:</label>
                        <input type="password" class="form-control" id="pwd" name="password">
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Ingresar</button>

                    </div>

                    <div class="form-group">
                        <a href="{% url 'principal:registro' %}" class="btn btn-link btn-sm">Registrarse</a>

                        <a class="btn btn-link btn-sm" href="{% url 'password_reset' %}">Recuperar Contraseña</a>

                    </div>
                </form>
            </div>
            {% else %}
            <div class="col-sm-4">
                <h5>User: {{ user.username }}</h5>
                <h5>Email: {{ user.email }}</h5>
                {% if rol == "INS" %}
                <a href="{% url 'instructor:index' %}" class="btn btn-primary btn-sm d-block mb-3 text-white">Iniciar dashboard</a>
                {% else %}
                <a href="{% url 'aprendiz:index' %}" class="btn btn-primary btn-sm d-block mb-3 text-white">Iniciar dashboard</a>
                {% endif %}
                <a href="{% url 'logout' %}" class="btn btn-danger btn-sm d-block text-white">cerrar session</a>
            </div>

            {% endif %}
        </div>
    </div>

</section>
{% endblock %}

templates/principal/introduccion.html
{% extends 'layouts/plantilla_principal.html' %}
{% load static %}
{% block contenido %}
<section>
     <aside>
          <div>
              <div class="row">
               <div class="col-sm-10">
                    <div id ="texto">
			        <h2>INTRODUCCIÓN </h2>
		            </div>


                     	<p class="lead"> Student Intelligent es una pagina Web  la cual los aprendices Sena puedan resolver inquietudes y dudas sobre sus trabajos, talleres o explicaciones que muchas veces el aprendiz no entiende en la formación.
        La App también permite a los Aprendices Sena formular preguntas como responderlas y en la cual se enfocara en el área de Desarrollo de Software, específicamente en el programa de Tgo. En Análisis y Desarrollo de Sistemas de Información (ADSI) del Centro de Diseño e Innovación Tecnológica Industrial de la Regional Risaralda.
        </p>



                     </div>
                </div>
          </div>
     </aside>

  </section>
{% endblock %}

templates/principal/justificacion.html
{% extends 'layouts/plantilla_principal.html' %}
{% load static %}
{% block contenido %}
<section>
    <aside>
        <div>
            <div class="row">
                <div class="col-sm-10">
                    <div id ="texto">
                        <h2>JUSTIFICACIÓN </h2>
                    </div>


                        <p class="lead"> Los motivos o razones por la cuales se lleva a cabo la creación de este proyecto son por la necesidad de crear una ayuda a partir de una estructuración de preguntas relacionadas con su área de formación, además la generaciones de  alternativas de aprendizaje que usen como recurso los dispositivos de la vida cotidiana. Estas temáticas fueron elegidas con el fin de generar un aprendizaje en el usuario ya que es  típico que general mente sele dificulten algunos temas, esta aplicación va a ser diseñada para dispositivos móviles ya que es un medio factible y común para ser difundida esta aplicación teniendo en cuenta que en la actualidad existen gran cantidad de celulares  </p>



                </div>
            </div>
        </div>
    </aside>

</section>
{% endblock %}

templates/principal/registro.html
{% extends 'layouts/plantilla_principal.html' %}
{% load static %}

{% block contenido %}
<section>
<hr>
<h1 class="text-center">Registrarse</h1>


{% include 'layouts/alertas.html' %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <hr>
    <h3>Datos Personales</h3>
    <div class="form-row">
        {% for item1 in form %}
            <div class="form-group col-sm-6">
                <label for="inputAddress">{{ item1.label }}</label>
                {{ item1 }}
            </div>
        {% endfor %}

    </div>
    <hr>
    <h3>Datos Usuarios</h3>
    <div class="form-row">
        {% for item2 in form2 %}
            <div class="form-group col-sm-6">
                <label for="inputAddress">{{ item2.label }}</label>
                {{ item2 }}
                {{ item2.help_text }}
            </div>
        {% endfor %}
        <div class="form-group col-sm-12">
            <input type="submit" name="kp-send" value="Registrarse">
        </div>
    </div>
</form>

</section>


{% endblock %}