aprendiz/urls.py
from django.urls import path
from aprendiz import views

app_name = "aprendiz"
urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('crear-preguntas/', views.CrearPregunta.as_view(), name="crearPreguntas"),
    path('editar_perfil/<int:pk>/', views.EditarPerfil.as_view(), name="editarPerfil"),
    path('eliminar_perfil/', views.EliminarPerfil.as_view(), name="eliminarPerfil"),
    path('preguntas/', views.VerPreguntas.as_view(), name="verPreguntas"),
    path('comentario/', views.InsertarComentario.as_view(), name="comentario")
]

foroStudent/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeDoneView, PasswordChangeView, PasswordResetView, \
    PasswordResetConfirmView, PasswordResetCompleteView, PasswordResetDoneView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from principal.views import Login, Logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('principal.urls', namespace="principal"), name="principal"),
    path('accounts/', include('aprendiz.urls', namespace="aprendiz"), name="aprendiz"),
    path('backoffice/', include('instructor.urls', namespace="instructor"), name="instructor"),
    path('login/', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),

    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<str:uidb64>/<str:token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aprendiz/models.py
from django.db import models

# Create your models here.

aprendiz/forms.py
from django import forms
from principal.models import Pregunta

class PreguntaForm(forms.ModelForm):
    class Meta:
        model = Pregunta
        fields = [
            "titulo",
            "descripcion"
        ]
        labels = {
            "titulo": "Titulo de la pregunta",
            "descripcion": "Descripcion detallada"
        }

    def __init__(self,*args, **kwargs):
        super(PreguntaForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

aprendiz/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView
from django.views.generic.base import View

from django.contrib.auth.models import User
from principal.models import Pregunta, InformacionPersonal, Comentario
from aprendiz.forms import PreguntaForm
from principal.forms import RegistroDatosForm, EditUserForm

# Create your views here.


class LoginAccess(LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):

        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse("principal:index"))

        try:
            datos = InformacionPersonal.objects.get(userid=request.user.pk)
            if datos.rol == "INS":
                return HttpResponseRedirect(reverse("instructor:index"))

        except InformacionPersonal.DoesNotExist:
            print("No se cargaron los datos del perfil")

        return super().dispatch(request, *args, **kwargs)


class Index(LoginAccess, View):
    login_url = '/'
    def get(self, request):
        try:
            datosPersonales = InformacionPersonal.objects.get(userid=request.user.pk)

            datos = {
                "nombre": datosPersonales.nombre,
                "apellido": datosPersonales.apellidos,
                "rol": datosPersonales.rol,
                "foto": datosPersonales.foto
            }

            return render(request, "aprendiz/index.html", datos)
        except InformacionPersonal.DoesNotExist:
            return HttpResponseRedirect("principal:index")


class CrearPregunta(CreateView):
    model = Pregunta
    template_name = "aprendiz/realizar_pregunta.html"
    form_class = PreguntaForm
    success_url = reverse_lazy("aprendiz:index")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(self.request.POST)

        if form.is_valid():
            datosPregunta = form.save(commit=False)

            info = InformacionPersonal.objects.get(userid=self.request.user.id)

            datosPregunta.userid = info
            datosPregunta.save()
            messages.add_message(request, messages.SUCCESS, "Tu pregunta ha sido posteada en el muro del instructor")
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))


class EditarPerfil(UpdateView):
    model = User
    template_name = "aprendiz/perfil_editar.html"
    form_class = RegistroDatosForm
    form2_class = EditUserForm
    success_url = reverse_lazy("aprendiz:index")

    def get_context_data(self, **kwargs):
        context = super(EditarPerfil, self).get_context_data(**kwargs)

        datos_personales = InformacionPersonal.objects.get(userid=self.request.user.pk)
        context["rol"] = datos_personales.rol

        context['form'] = self.form_class(rol=datos_personales,instance=datos_personales)
        if 'form2' not in context:
            context['form2'] = self.form2_class(instance=self.request.user)

        return context

    def post(self, request, *args, **kwargs):

        self.object = self.get_object
        datos_personales = InformacionPersonal.objects.get(userid=self.request.user.pk)
        rol = datos_personales.rol

        form = self.form_class(datos_personales.rol,self.request.POST, self.request.FILES,instance=datos_personales)
        form2 = self.form2_class(self.request.POST, instance=request.user)

        if form.is_valid() and form2.is_valid():
            form = form.save(commit=False)

            form.rol = rol
            form.save()
            form2.save()


            messages.add_message(request, messages.SUCCESS, "Has actualizado tu perfil con exito")
            return HttpResponseRedirect(self.get_success_url())
        else:
            messages.add_message(request, messages.ERROR, "No se han llenado todos los campos")
            return self.render_to_response(self.get_context_data(form=form, form2=form2))

class EliminarPerfil(View):

    def get(self, request):
        url = request.GET.get("next","/accounts")

        return HttpResponseRedirect(url)

    def post(self, request):
        try:
            usuario = User.objects.get(pk=request.user.pk)
        except:
            messages.add_message(request, messages.ERROR, "Lo sentimos hay un error en este perfil, prueba denuevo o comunicate con el administrador")
            return HttpResponseRedirect(reverse("principal:index"))

        url = request.GET.get("next", "/accounts")


        if usuario.delete():
            messages.add_message(request, messages.SUCCESS, "Has eliminado este usuario con exito")
        else:
            messages.add_message(request, messages.ERROR, "Hubo un problema al eliminar el usuario")


        return HttpResponseRedirect(url)

class VerPreguntas(ListView):
    model = Pregunta
    template_name = "aprendiz/preguntas.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            userid = InformacionPersonal.objects.get(userid=self.request.user.pk)

            context['object_list'] = Pregunta.objects.filter(userid=userid.pk)


            datos = InformacionPersonal.objects.get(userid=self.request.user.pk)


            context["comentario"] = Comentario.objects.filter(pregid__userid=userid.pk)
        except InformacionPersonal.DoesNotExist:
            messages.add_message(self.request,messages.WARNING, "Precaucion un error al cargar iformacion de perfil")
        return context

class InsertarComentario(View):
    def get(self,request):
        return HttpResponseRedirect(reverse("aprendiz:index"))
    def post(self,request):
        datos = request.POST.get("comentario")
        id_pregunta = request.POST.get("id_preg")

        comentario = Comentario()
        comentario.userid = InformacionPersonal.objects.get(userid=request.user)
        comentario.contenido = datos
        comentario.pregid = Pregunta.objects.get(id=id_pregunta)

        comentario.save()
        return HttpResponseRedirect(reverse("aprendiz:verPreguntas"))

templates/aprendiz/index.html
{% extends 'layouts/plantilla_aprendiz.html' %}
{% load static %}
{% block contenido %}
<section>
    <div style="margin-top:50px">
        <div class="row">
            <div class="col-sm-8">
                {% include 'layouts/alertas.html' %}
                <h2>{{ user.username }} | {{ user.email }}</h2>
                <div id="demo" class="carousel slide" data-ride="carousel">

                    <!-- Indicators -->
                    <ul class="carousel-indicators">
                        <li data-target="#demo" data-slide-to="0" class="active"></li>
                        <li data-target="#demo" data-slide-to="1"></li>
                        <li data-target="#demo" data-slide-to="2"></li>
                    </ul>

                    <!-- The slideshow -->
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="{% static 'imagenes/4545168.jpg' %}" class="img-fluid">
                        </div>
                        <div class="carousel-item">
                            <img src="{% static 'imagenes/6786872.jpg' %}" class="img-fluid">
                        </div>
                        <div class="carousel-item">
                            <img src="{% static 'imagenes/64785.jpg' %}" class="img-fluid">
                        </div>
                    </div>

                    <!-- Left and right controls -->
                    <a class="carousel-control-prev" href="#demo" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                    </a>
                    <a class="carousel-control-next" href="#demo" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                    </a>

                </div>

            </div>

            <div class="col-sm-4">
                <div class="card">
                    <img class="card-img-top" src="{{ foto.url }}" alt="Card image">
                    <div class="card-body">
                        <h4 class="card-title">{{ nombre }} {{ apellido }}</h4>
                        <p class="card-text">{{ rol|capfirst }}</p>
                        <a href="{% url 'aprendiz:editarPerfil' user.pk %}" class="btn btn-primary btn-sm">Editar perfil</a>
                        <div class="mt-2">
                            <a href="{% url 'password_change' %}?prev=accounts/" class="btn btn-outline-secondary btn-sm">clave</a>
                            <a href="#" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal">eliminar cuenta</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'aprendiz:eliminarPerfil' %}?next=/accounts">{% csrf_token %}
                    <p>Estas seguro de eliminar este usuario "{{ nombre }} {{ apellido }}" y vinculado a un usuario ({{ user.username }}) y email({{ user.email }})?</p>
                    <input type="submit" value="Confirm">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/aprendiz/perfil_editar.html
{% extends 'layouts/plantilla_aprendiz.html' %}
{% load static %}

{% block contenido %}
<section>
<hr>
<h1 class="text-center">Editar Perfil</h1>

{% if form.errors %}
<div class="alert alert-danger">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong>DatosPersonales!</strong> {{ form.errors }}
</div>
{% endif %}

{% if form2.errors and method == "POST" %}
<div class="alert alert-danger">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong>Usuario!</strong> {{ form2.errors }}
</div>
{% endif %}


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        {% for item1 in form %}
            <div class="form-group col-sm-6">
                <label for="inputAddress">{{ item1.label }}</label>
                {{ item1 }}
            </div>
        {% endfor %}

    </div>
    <hr>
    <h3>Datos personales</h3>
    <div class="form-row">
        {% for item2 in form2 %}
            <div class="form-group col-sm-6">
                <label for="inputAddress">{{ item2.label }}</label>
                {{ item2 }}
            </div>
        {% endfor %}
        <div class="form-group">
            <input type="submit" name="kp-send" class="btn btn-success" value="Actualizar">
        </div>
    </div>
</form>

</section>


{% endblock %}

templates/aprendiz/perfil_eliminar.html
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'aprendiz:eliminarPerfil' %}?next=/accounts">{% csrf_token %}
                    <p>Estas seguro de eliminar este usuario "{{ nombre }} {{ apellido }}" y vinculado a un usuario ({{ user.username }}) y email({{ user.email }})?</p>
                    <input type="submit" value="Confirm">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

templates/aprendiz/preguntas.html
{% extends 'layouts/plantilla_aprendiz.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/style-instructor.css' %}">
{% endblock %}
{% block contenido %}
<section>
<h2>Preguntas </h2>
    {% if object_list %}
        {% for pregunta in object_list %}
        <div id="accordion" class="mb-3">
            <div class="card mb-3">
                <div class="card-header">
                    <a class="card-link" data-toggle="collapse" href="#collapse{{ pregunta.id }}">
                        <div class="media border p-3">
                            <img src="{{ pregunta.userid.foto.url }}" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
                            <div class="media-body">
                                <h4>{{ pregunta.userid.nombre }} {{ pregunta.userid.apellidos }} <small> <i>Posted on {{ pregunta.fecha }}</i></small></h4>
                                <p>
                                    <h5 class="mb-0">{{ pregunta.titulo }}</h5>
                                    {{ pregunta.descripcion }}
                                </p>
                            </div>
                        </div>
                    </a>
                </div>
                <div id="collapse{{ pregunta.id }}" class="collapse" data-parent="#accordion">
                    <div class="card-body">
                        <a href="#demo{{ pregunta.id }}" data-toggle="collapse" class="btn btn-secondary">Ver mas comentarios</a>
                        <div id="demo{{ pregunta.id }}" class="collapse">
                            {% for coment in comentario %}
                                {% if coment.pregid.id == pregunta.id %}
                                <div class="media border p-3">
                                    <div class="media-body">
                                        <h4>{{ coment.userid.nombre }} {{ coment.userid.apellidos }}<small> <i>Posted on {{ coment.fecha }}</i></small></h4>
                                        <p>{{ coment.contenido }}</p>
                                    </div>
                                    <img src="{{ coment.userid.foto.url }}" alt="John Doe" class="ml-3 mt-3 rounded-circle" style="width:60px;">
                                </div>
                                <br>
                                {% endif %}
                            {% endfor %}
                        </div>


                        <form action="{% url 'aprendiz:comentario' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="id_preg" value="{{ pregunta.id }}">
                            <div class="form-group">
                                <label for="comment">Comentario:* </label>
                                <textarea class="form-control" rows="5" id="comment" name="comentario" required></textarea>
                            </div>
                            <button type="reset" class="btn btn-outline-primary float-right ">Cancelar</button>
                            <button type="submit" class="btn btn-outline-primary float-right mr-2">Guardar</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
        {% endfor %}

    {% else %}
        <div class="alert alert-info">
            <h2>Lo sentimos</h2>
            <p>no se han encontrado registros de preguntas</p>
        </div>
    {% endif %}

</section>
{% endblock %}

templates/aprendiz/realizar_pregunta.html
{% extends 'layouts/plantilla_aprendiz.html' %}
{% load static %}

{% block contenido %}
<section>
<hr>
<h1 class="text-center">Realizar pregunta</h1>

{% if form.errors %}
<div class="alert alert-danger">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong>DatosPersonales!</strong> {{ form.errors }}
</div>

{% else %}
<div class="alert alert-warning">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong>Nota!</strong>
    <p>Recuerda escribir bien la pregunta y detalladamente usando titulo y descripcion, si te equivocas no podra ser corregido, tendras que reescribir una nueva</p>
</div>
{% endif %}


<form method="post">
    {% csrf_token %}
    <div class="form-row">

        {% for item in form %}
            <div class="form-group col-sm-12">
                <label for="inputAddress">{{ item.label }}</label>
                {{ item }}
            </div>
        {% endfor %}
        <div class="form-group">
            <input type="submit" name="kp-send" value="Preguntar" class="btn btn-outline-primary">
        </div>
    </div>
</form>

</section>


{% endblock %}